package edu.rit.se;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class SwatchFactory
{
	/**
	 * Generate a swatch of the given name. If the swatch exists in the
	 * filesystem, then we build the swatch from that persisted file.
	 * Otherwise, we start with an empty swatch.
	 * 
	 * The swatch file is generated by combining the swatch name with the
	 * swatch file extension (.txt).
	 * 
	 * @param name
	 *        The name of the swatch.
	 * @return The generated swatch
	 */
	public static Swatch byName(String name)
	{
		List<Color> colors = new ArrayList<Color>();

		File f = new File(name + Swatch.EXT);
		BufferedReader r = null;
		try {
			r = new BufferedReader(new FileReader(f));
			String line;
			int num = 0;
			while ((line = r.readLine()) != null) {
				if (num++ < 1) continue; // Skip name of swatch

				Color c = ColorFactory.fromString(line);
				if (c != null) {
					colors.add(c);
				}
			}

			return new Swatch(name, colors);

		} catch (FileNotFoundException e) {
			return empty(name);
		} catch (IOException e) {
			return empty(name);
		} finally {
			if (r != null) {
				try {
					r.close();
				} catch (IOException e) {
				}
			}
		}
	}

	public static Swatch empty(String name)
	{
		return new Swatch(name, new ArrayList<Color>());
	}
}
